### ISSUE TITLE
multiple errors...

### ISSUE THREAD

**Issue by viperdriver2000** [stdevel/check_dht#1]
Hi,
i try to use your script but i get only errors :(

```
pi@bastel-pi:~/temperature/Adafruit_Python_DHT $ ./check_dht.py -s AM2302 -H -d -g 7 -W 25 -C 30
DEBUG:check_dht:{'warningHumiThres': 25, 'humiOnly': True, 'tempUnit': 'celsius', 'tempOnly': False, 'sensorType': 'AM2302', 'warningTempThres': 0, 'criticalHumiThres': 30, 'criticalTempThres': 0, 'debug': True, 'sensorPin': 7}
Traceback (most recent call last):
  File "./check_dht.py.1", line 125, in <module>
    humidity, temperature = Adafruit_DHT.read_retry(sensor, options.sensorPin)
  File "/opt/temperature/Adafruit_Python_DHT/Adafruit_DHT/common.py", line 90, in read_retry
    humidity, temperature = read(sensor, pin, platform)
  File "/opt/temperature/Adafruit_Python_DHT/Adafruit_DHT/common.py", line 76, in read
    platform = get_platform()
  File "/opt/temperature/Adafruit_Python_DHT/Adafruit_DHT/common.py", line 48, in get_platform
    from . import Raspberry_Pi
  File "/opt/temperature/Adafruit_Python_DHT/Adafruit_DHT/Raspberry_Pi.py", line 22, in <module>
    from . import Raspberry_Pi_Driver as driver
ImportError: cannot import name Raspberry_Pi_Driver
```
cloned yesterday the Adafruit_Python_DHT git. i think there was changes that make your script wont work any more.

do you still use your own script?
do you make an update?

**Comment by viperdriver2000** [comment]
okay...if i run the script in another directory as Adafruit_Python_DHT then it works...
